// @ts-check
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default [
  {
    ignores: [
      "dist/**",
      ".test-build/**",
      "node_modules/**",
      "test-output.log",
      "e2e-output.log",
      "lint-err.txt",
      "client/vendor/**",
      "client/src/**",
      "prism-ui-design-mcp/**",
      ".tmp-shot/**",
      ".prism-previews/**",
      "test-results/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    files: ["**/*.ts"],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-unused-vars": "off",
      "no-empty": "warn",
      "no-useless-escape": "warn",
    },
  },
  {
    files: ["client/**/*.js"],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": "warn",
      "no-useless-escape": "warn",
    },
  },
  // Split client modules are global-scope scripts loaded in order; every
  // module can see the shared top-level identifiers declared by the others.
  {
    files: ["client/app-*.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        $: "readonly", ALIGN_ACTIONS: "readonly", BUILTIN_TEMPLATES: "readonly",
        CURSOR_THROTTLE: "readonly", ELEMENT_BEHAVIOR_TYPES: "readonly",
        EXAMPLE_PROMPTS: "readonly", I18N: "readonly", LIBRARY_ANIMATIONS: "readonly",
        LIBRARY_BLOCKS: "readonly", LIBRARY_COMPONENTS: "readonly",
        LIBRARY_INTERACTIONS: "readonly", LIBRARY_TEMPLATES: "readonly",
        MAX_RECONNECT: "readonly", PAGE_BACKGROUND_ANIM_CSS: "readonly",
        PAGE_BACKGROUND_PRESETS: "readonly", PLATFORMS: "readonly",
        QUICK_CHIP_PROMPTS: "readonly", RECONNECT_DELAY: "readonly",
        RESIZE_DIRS: "readonly", SNAP_THRESHOLD: "readonly",
        activeDrawTool: "writable", activeTokenTab: "writable",
        activitySearchQuery: "writable", activitySourceFilter: "writable",
        addActivityEntry: "readonly", addComponentViaAPI: "readonly",
        alignSelected: "readonly", appliedDrawIds: "readonly",
        applyAnimation: "readonly", applyBehaviorTemplateViaAPI: "readonly",
        applyCanvasMode: "readonly", applyCanvasToPreview: "readonly",
        applyComponentTemplateViaAPI: "readonly", applyDrawToolsState: "readonly",
        applyElementMetaStyles: "readonly", applyElementSelectionHighlight: "readonly",
        applyI18n: "readonly", applyPageBackground: "readonly",
        applyPendingCanvasDraws: "readonly", applyPlatform: "readonly",
        applyPromptResult: "readonly", applyStyleProps: "readonly",
        applyTemplateForCanvas: "readonly", applyTemplateViaAPI: "readonly",
        applyTheme: "readonly", applyTokensToCanvas: "readonly",
        attachDragHandlers: "readonly", attachFreeformDrag: "readonly",
        attachGuideDrag: "readonly", attachLayerRenameDoubleClick: "readonly",
        attachResizeHandles: "readonly", autoLayout: "readonly",
        buildAnimationPreview: "readonly", buildCanvasBehavior: "readonly",
        buildChromeBottom: "readonly", buildChromeTop: "readonly",
        buildCommands: "readonly", buildComponentPreview: "readonly",
        canvasBundlePromise: "writable", canvasDirty: "writable",
        canvasEditorMode: "writable", canvasEditorMounted: "writable",
        canvasGuides: "writable", canvasLoading: "writable",
        canvasMode: "writable", canvasOwnSaveAt: "writable",
        canvasReady: "writable", canvasSaveTimer: "writable",
        canvasTemplateShownForPage: "writable", canvasZoom: "writable",
        channelLuminance: "readonly", checkConflicts: "readonly",
        clearCanvasEditor: "readonly", clearDragIndicators: "readonly",
        clearElementSelection: "readonly", clearSnapLines: "readonly",
        closeCommandPalette: "readonly", commandActiveIndex: "writable",
        commandItems: "writable", commandPaletteOpen: "writable",
        componentParentPath: "readonly", conflictCheckInterval: "writable",
        connect: "readonly", copyToClipboard: "readonly",
        countComponents: "readonly", cssAnimName: "readonly",
        currentExportFormat: "writable", currentLibraryTab: "writable",
        currentPlatform: "writable", currentState: "writable",
        currentToolTab: "writable", deselectAll: "readonly",
        dispatchBehavior: "readonly", dispatchCanvasShapeBehavior: "readonly",
        dispatchElementBehavior: "readonly", downloadHTML: "readonly",
        draggedComponentId: "writable", duplicateSelected: "readonly",
        editableText: "readonly", el: "readonly", elementBehaviorAt: "readonly",
        ensureCanvasBundle: "readonly", ensureFreeformLayouts: "readonly",
        examplePromptText: "readonly", exportCanvasToFile: "readonly",
        fetchExportCode: "readonly", fetchInitialState: "readonly",
        findAllComponents: "readonly", findCompDeep: "readonly",
        flashButton: "readonly", formatTime: "readonly",
        frameRectInWrap: "readonly", getAnimationTarget: "readonly",
        getCanvasInlineStyles: "readonly", getCompById: "readonly",
        getCurrentComponents: "readonly", getSelectedComp: "readonly",
        getSelectedComps: "readonly", getSliderRange: "readonly",
        handleChange: "readonly", handleDeleteComponent: "readonly",
        handleLibraryDrop: "readonly", handleLibraryItemClick: "readonly",
        handleMessage: "readonly", hasClickableBehavior: "readonly",
        hideLibraryPreview: "readonly", hidePromptSuggestions: "readonly",
        init: "readonly", initializeFreeformLayouts: "readonly",
        inspectorCodeFormat: "writable", isColorValue: "readonly",
        isInspectorFocused: "readonly", isNumericToken: "readonly",
        lastCursorSent: "writable", layerLastClickAt: "writable",
        layerLastClickId: "writable", libraryReplaceMode: "writable",
        librarySearchQuery: "writable", loadCanvasIntoEditor: "readonly",
        markElement: "readonly", modalClose: "readonly",
        moveCommandActive: "readonly", moveSelected: "readonly",
        myClientId: "writable", normalizeColorForPicker: "readonly",
        openExplainModal: "readonly", openHtmlScreenshot: "readonly",
        pageBgAnimStyleEl: "writable", parseHex: "readonly",
        pendingDrawTool: "writable", perfTime: "readonly", exposePerf: "readonly",
        playComponentAnimation: "readonly", playMode: "writable",
        promptStatusTimer: "writable", promptSuggestTimer: "writable",
        reconnectAttempts: "writable", relativeLuminance: "readonly",
        remoteCursors: "readonly", renderAccordion: "readonly",
        renderActivityLog: "readonly", renderAlert: "readonly",
        renderAll: "readonly", renderAvatar: "readonly", renderBadge: "readonly",
        renderBanner: "readonly", renderBentoGrid: "readonly",
        renderBreadcrumb: "readonly", renderButton: "readonly",
        renderCanvas: "readonly", renderCanvasTemplateCards: "readonly",
        renderCard: "readonly", renderCardGrid: "readonly",
        renderCarousel: "readonly", renderCommandList: "readonly",
        renderCommandPalette: "readonly", renderComments: "readonly",
        renderComponent: "readonly", renderComponentContent: "readonly",
        renderConflictWarnings: "readonly", renderContainer: "readonly",
        renderCookieBanner: "readonly", renderCta: "readonly",
        renderDesignSystems: "readonly", renderElementPanel: "readonly",
        renderExplain: "readonly", renderFab: "readonly", renderFaq: "readonly",
        renderFeatureGrid: "readonly", renderFeatureList: "readonly",
        renderFooter: "readonly", renderForm: "readonly",
        renderGeneric: "readonly", renderGlassCard: "readonly",
        renderGrid: "readonly", renderGuides: "readonly",
        renderHelpShortcuts: "readonly", renderHero: "readonly",
        renderImage: "readonly", renderImportBanner: "readonly",
        renderInput: "readonly", renderInspector: "readonly",
        renderInspectorCode: "readonly", renderInspectorProps: "readonly",
        renderLayerPanel: "readonly", renderLibraryList: "readonly",
        renderMarquee: "readonly", renderModalComponent: "readonly",
        renderNavbar: "readonly", renderPageBackgroundPanel: "readonly",
        renderPageSwitcher: "readonly", renderPagination: "readonly",
        renderPricing: "readonly", renderProgress: "readonly",
        renderProjectList: "readonly", renderRemoteCursors: "readonly",
        renderRulers: "readonly", renderSavedTemplates: "readonly",
        renderSection: "readonly", renderSelectionToolbar: "readonly",
        renderSidebar: "readonly", renderSkeleton: "readonly",
        renderStats: "readonly", renderTable: "readonly",
        renderTabs: "readonly", renderTestimonial: "readonly",
        renderText: "readonly", renderTextSection: "readonly",
        renderTimeline: "readonly", renderToggle: "readonly",
        renderTokenPanel: "readonly", renderTooltip: "readonly",
        renderTplThumb: "readonly", renderVersions: "readonly",
        replaceComponentViaAPI: "readonly", rulerZoom: "readonly",
        runCommandItem: "readonly", saveCurrentAsTemplate: "readonly",
        saveCurrentCanvas: "readonly", saveCurrentProject: "readonly",
        saveElementMeta: "readonly", savePageBackground: "readonly",
        selectComponent: "readonly", selectDrawTool: "readonly",
        selectElement: "readonly", selectedComponentId: "writable",
        selectedElementPath: "writable", selectedIds: "writable",
        send: "readonly", sendPrompt: "readonly", sendSetAnimation: "readonly",
        sendTokenUpdate: "readonly", sendUpdateComponent: "readonly",
        setCanvasEditorMode: "readonly", setPromptStatus: "readonly",
        setupActivityFilter: "readonly", setupApplyBanner: "readonly",
        setupCanvasBehavior: "readonly", setupCanvasDrawing: "readonly",
        setupCanvasDropZone: "readonly",
        setupCanvasMode: "readonly", setupCanvasPlayClick: "readonly",
        setupCanvasShortcuts: "readonly", setupCommandPalette: "readonly",
        setupCommentsPanel: "readonly", setupConflictCheck: "readonly",
        setupDesignLibrary: "readonly", setupDrawTools: "readonly",
        setupExplain: "readonly", setupExportModal: "readonly",
        setupI18n: "readonly", setupImportModal: "readonly",
        setupInlineEditing: "readonly", setupLibrarySearch: "readonly",
        setupLiveCursors: "readonly", setupLlmSettings: "readonly",
        setupMoreMenu: "readonly", setupPageSwitcher: "readonly",
        setupPlatformSwitcher: "readonly", setupPlayMode: "readonly",
        setupProjectPersistence: "readonly", setupPromptBar: "readonly",
        setupPromptChips: "readonly", setupQuickActions: "readonly",
        setupRulersAndGuides: "readonly", setupScreenshot: "readonly",
        setupTabs: "readonly", setupThemeToggle: "readonly",
        setupTokenSearch: "readonly", setupToolTabs: "readonly",
        setupUndoRedo: "readonly", setupVersionsPanel: "readonly",
        setupWriteback: "readonly", setupZoom: "readonly",
        showConflictWarning: "readonly", showLibraryPreview: "readonly",
        showPromptSuggestions: "readonly", showSnapLine: "readonly",
        showToastMsg: "readonly", snapCandidates: "readonly",
        snapLayout: "readonly", snapValue: "readonly",
        startGuideFromRuler: "readonly", startLayerRename: "readonly",
        startPageRename: "readonly", syncPlatformFromState: "readonly",
        clearPrismFragElementSelection: "readonly", commitFragmentHtml: "readonly",
        fragElementByPath: "readonly", prismFragElementSel: "writable",
        selectPrismFragElement: "readonly",
        t: "readonly", takeScreenshot: "readonly", toastTimer: "writable",
        toggleCommandPalette: "readonly", toggleHelp: "readonly",
        tokenSearchQuery: "writable", tplThumbBlocks: "readonly",
        uiLang: "writable", updateCommandActive: "readonly",
        updateLlmBadge: "readonly", updateStatus: "readonly",
        updateUndoRedoButtons: "readonly", wcagContrastRatio: "readonly",
        ws: "writable", zOrderSelected: "readonly",
        window: "readonly", document: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": "warn",
      "no-useless-escape": "warn",
      "no-undef": "error",
      // Split modules intentionally share one global namespace: each file
      // re-declares shared identifiers (let/const/function), so collisions
      // between a file's own declarations and the cross-file globals are
      // expected. `no-redeclare` would flag every shared symbol.
      "no-redeclare": "off",
      "@typescript-eslint/no-redeclare": "off",
    },
  },
  {
    files: ["tests/**/*.ts"],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
  },
  {
    files: ["electron/**/*.{js,cjs}"],
    languageOptions: {
      globals: globals.node,
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-require-imports": "off",
    },
  },
];
