/**
 * Design-token interoperability (improvement plan B3).
 *
 * Converts the internal token shape `{ value, source }` to and from:
 *   - W3C DTCG JSON   (`$value` / `$type` / `$description`)
 *   - CSS custom properties
 *   - Style Dictionary nested JSON
 *
 * DTCG types follow the stable 2025-10 specification (design-tokens
 * community group). Unknown values are kept as-is and typed `string`.
 */

import type { DesignTokens, DesignToken } from "../state.js";
import { load as parseYaml, dump as stringifyYaml } from "js-yaml";

export type DtcgExportFormat =
  | "dtcg"
  | "css"
  | "style-dictionary"
  | "figma_tokens"
  | "design_md"
  | "tailwind";

export interface DtcgToken {
  $type: string;
  $value: string;
  $description?: string;
  $extensions?: { "prism.source"?: string };
}

const DTCG_TYPE_BY_CATEGORY: Record<keyof DesignTokens, string> = {
  colors: "color",
  typography: "fontFamily",
  spacing: "dimension",
  shadows: "shadow",
  radii: "borderRadius",
  transitions: "transition",
};

/** Refine DTCG type for common typography token keys. */
function dtcgTypeFor(category: string, key: string): string {
  if (category === "typography") {
    if (key.startsWith("text-")) return "fontSize";
    if (key.startsWith("font-weight")) return "fontWeight";
    if (key.startsWith("line-height")) return "lineHeight";
    if (key.startsWith("font-")) return "fontFamily";
  }
  return DTCG_TYPE_BY_CATEGORY[category as keyof DesignTokens] || "string";
}

/** Convert the internal token store to DTCG JSON. */
export function tokensToDtcg(tokens: DesignTokens): Record<string, Record<string, DtcgToken>> {
  const result: Record<string, Record<string, DtcgToken>> = {};
  (Object.keys(tokens) as Array<keyof DesignTokens>).forEach((category) => {
    const entries = tokens[category];
    if (!entries || Object.keys(entries).length === 0) return;
    result[category] = {};
    Object.entries(entries).forEach(([key, token]) => {
      const entry: DtcgToken = {
        $type: dtcgTypeFor(category, key),
        $value: token.value,
      };
      if (token.description) entry.$description = token.description;
      if (token.source) entry.$extensions = { "prism.source": token.source };
      result[category][key] = entry;
    });
  });
  return result;
}

/** Convert the internal token store to flat CSS custom properties. */
export function tokensToCss(tokens: DesignTokens): string {
  const lines = [":root {"];
  (Object.keys(tokens) as Array<keyof DesignTokens>).forEach((category) => {
    Object.entries(tokens[category] || {}).forEach(([key, token]) => {
      lines.push(`  --${key}: ${token.value};`);
    });
  });
  lines.push("}");
  return lines.join("\n");
}

/** Convert the internal token store to Style Dictionary nested JSON. */
export function tokensToStyleDictionary(tokens: DesignTokens): Record<string, Record<string, { value: string }>> {
  const result: Record<string, Record<string, { value: string }>> = {};
  (Object.keys(tokens) as Array<keyof DesignTokens>).forEach((category) => {
    const entries = tokens[category];
    if (!entries || Object.keys(entries).length === 0) return;
    result[category] = {};
    Object.entries(entries).forEach(([key, token]) => {
      result[category][key] = { value: token.value };
    });
  });
  return result;
}

/** Tailwind v4 CSS-first export: an `@theme` block mapping tokens to CSS variables. */
export function tokensToTailwind4(tokens: DesignTokens): string {
  const lines = ["@theme {"];
  (Object.keys(tokens) as Array<keyof DesignTokens>).forEach((category) => {
    Object.entries(tokens[category] || {}).forEach(([key, token]) => {
      lines.push(`  --${key}: ${token.value};`);
    });
  });
  lines.push("}");
  return lines.join("\n");
}

/**
 * Export tokens as a Google DESIGN.md document: YAML front matter holding the
 * token groups plus a short prose section describing usage.
 */
export function tokensToDesignMd(tokens: DesignTokens, name: string, prose?: string): string {
  const frontMatter: Record<string, unknown> = {
    name,
    version: "1",
  };
  (Object.keys(tokens) as Array<keyof DesignTokens>).forEach((category) => {
    const entries = tokens[category];
    if (!entries || Object.keys(entries).length === 0) return;
    const group: Record<string, string> = {};
    Object.entries(entries).forEach(([key, token]) => {
      group[key] = token.value;
    });
    frontMatter[category] = group;
  });

  const body = prose
    ? prose
    : `# ${name}\n\nDesign tokens generated by Prism. Tokens are defined in the YAML front matter and consumed by the design tools.\n\n## Usage\n\n- Colors drive surfaces, text, and accents.\n- Typography scales are computed from a modular ratio.\n- Spacing, radii, shadows, and transitions keep density and elevation consistent.`;

  return `---\n${stringifyYaml(frontMatter)}---\n\n${body}\n`;
}

export interface DesignMdDocument {
  tokens: Partial<Record<keyof DesignTokens, Record<string, string>>>;
  prose: string;
  frontMatter: Record<string, unknown>;
}

/**
 * Parse a DESIGN.md document: extract the YAML front matter (between leading
 * `---` markers) and map token groups back to flat per-category token maps.
 */
export function parseDesignMd(markdown: string): DesignMdDocument {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(markdown);
  if (!match) {
    throw new Error("Invalid DESIGN.md: missing YAML front matter");
  }
  const frontMatter = parseYaml(match[1]) as Record<string, unknown>;
  if (!frontMatter || typeof frontMatter !== "object") {
    throw new Error("Invalid DESIGN.md: front matter is not an object");
  }
  const prose = markdown.slice(match[0].length).trim();

  const tokens: Partial<Record<keyof DesignTokens, Record<string, string>>> = {};
  const KNOWN: Array<keyof DesignTokens> = ["colors", "typography", "spacing", "shadows", "radii", "transitions"];
  for (const category of KNOWN) {
    const group = frontMatter[category];
    if (!group || typeof group !== "object") continue;
    const map: Record<string, string> = {};
    Object.entries(group as Record<string, unknown>).forEach(([key, value]) => {
      if (typeof value === "string") map[key] = value;
    });
    if (Object.keys(map).length > 0) tokens[category] = map;
  }
  if (Object.keys(tokens).length === 0) {
    throw new Error("Invalid DESIGN.md: no recognized token groups in front matter");
  }
  return { tokens, prose, frontMatter };
}

export interface ImportTokensOptions {
  merge: "replace" | "merge-overwrite" | "merge-keep";
}

/**
 * Parse DTCG JSON (grouped by category, each token with `$value`/`$type`)
 * into flat per-category token maps. Also accepts a flat `{ key: "$value" }`
 * object for convenience.
 */
export function dtcgToTokenMaps(
  json: unknown
): Partial<Record<keyof DesignTokens, Record<string, string>>> {
  if (!json || typeof json !== "object") {
    throw new Error("Invalid tokens JSON: expected an object");
  }
  const result: Partial<Record<keyof DesignTokens, Record<string, string>>> = {};
  const groups = json as Record<string, unknown>;

  Object.entries(groups).forEach(([category, group]) => {
    if (!group || typeof group !== "object") return;
    const map: Record<string, string> = {};
    Object.entries(group as Record<string, unknown>).forEach(([key, value]) => {
      if (value && typeof value === "object" && "$value" in (value as Record<string, unknown>)) {
        map[key] = String((value as Record<string, unknown>).$value);
      } else if (typeof value === "string") {
        map[key] = value;
      }
    });
    if (Object.keys(map).length > 0) {
      result[category as keyof DesignTokens] = map;
    }
  });

  if (Object.keys(result).length === 0) {
    throw new Error("No tokens found in the provided JSON");
  }
  return result;
}

/**
 * Apply imported token maps to the state store.
 * `replace` clears each category first; `merge-overwrite` overwrites matching
 * keys; `merge-keep` only writes keys that do not already exist.
 */
export function applyImportedTokens(
  store: {
    getState(): { tokens: DesignTokens };
    setToken(category: keyof DesignTokens, key: string, value: string, source: "ai" | "user", description?: string): void;
    clearTokenCategory(category: keyof DesignTokens): void;
  },
  maps: Partial<Record<keyof DesignTokens, Record<string, string>>>,
  options: ImportTokensOptions,
  source: "ai" | "user" = "user"
): number {
  const existing = store.getState().tokens;
  let count = 0;
  (Object.keys(maps) as Array<keyof DesignTokens>).forEach((category) => {
    const incoming = maps[category];
    if (!incoming) return;
    if (options.merge === "replace") {
      store.clearTokenCategory(category);
    }
    Object.entries(incoming).forEach(([key, value]) => {
      if (options.merge === "merge-keep" && existing[category][key]) return;
      store.setToken(category, key, value, source);
      count++;
    });
  });
  return count;
}

export function sampleToken(tokens: DesignTokens): DesignToken {
  const first =
    Object.values(tokens.colors)[0] ||
    Object.values(tokens.typography)[0] ||
    Object.values(tokens.spacing)[0] ||
    { value: "", source: "preset" as const };
  return first;
}
